// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MousePoint: typeof import('./src/components/MousePoint.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    Rate: typeof import('./src/components/Rate.vue')['default']
    Todolist: typeof import('./src/components/Todolist.vue')['default']
  }
}

export { }
